import rasterize.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * Vlastní examples.Canvas, který využívá RasterBufferedImage a LineRasterizer.
 */
public class MyCanvas {
    private JPanel panel;
    private RasterBufferedImage raster;
    private FilledLineRasterizer filledLineRasterizer;
    private DottedLineRasterizer dottedLineRasterizer;

    // Vytvoreni pointu jakozto zakladni pozice
    private Point startedPoints = new Point();

    public MyCanvas(int width, int height) {
        // Instance okna
        JFrame frame = new JFrame();
        // Layout okna
        frame.setLayout(new BorderLayout());
        // Titulek okna
        frame.setTitle("UHK FIM PGRF : " + this.getClass().getName());
        // Není možné měnit velikost okna
        frame.setResizable(false);
        // Pokud by zde nebylo, po zavření okna by se neukončila aplikace, důležité!
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        // Instance rasteru. Můžeme mít různé rastery.
        raster = new RasterBufferedImage(width, height);
        // Filled line rasterizer s upravenym trivialnim algoritmem
        filledLineRasterizer = new FilledLineRasterizer(raster);
        dottedLineRasterizer = new DottedLineRasterizer(raster);

        // Vytvoříme panel, který umí vykreslit BufferedImage
        panel = new JPanel() {
            private static final long serialVersionUID = 1L;

            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                // Vykreslíme BufferedImage
                present(g);
            }
        };
        // Velikost panelu
        panel.setPreferredSize(new Dimension(width, height));

        // Panel přidáme do okna, okno zvětšíme na jeho obsah, okno nastavíme jako viditelné
        frame.add(panel, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);

        // Key listener pro zachytravani eventu klavesnice
        panel.requestFocus();
        panel.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == 67) {
                    raster.setClearColor(0xFFFFFF);
                    raster.clear();
                    System.out.println("Platno bylo vymazano");
                }
            }
        });
        // Odchytavani mouse eventu pro click
        panel.addMouseListener(new MouseListener() {

            @Override
            public void mousePressed(MouseEvent e) {
                System.out.println("Mouse pressed");
                // Vytvor novy point s aktualnimi daty
                startedPoints = new Point(e.getX(), e.getY());
            }

            // Autogenerated methods
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println("Add polygon points");
                System.out.println();
                startedPoints = new Point(e.getX(), e.getY());

                // Pokud pointy nejsou prazdne!!!!
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                System.out.println("Mouse released");

                // Pokud mam jen jeden point kreslim
                drawLine(startedPoints.x, startedPoints.y, e.getX(), e.getY(), new Color(0xffffff), false);
            }

            @Override
            public void mouseEntered(MouseEvent e) {}

            @Override
            public void mouseExited(MouseEvent e) {}
        });
        // Mouse listener na panel pro zachytavani eventu mysi
        panel.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                super.mouseDragged(e);
                // Vycisti raster pred kreslenim
                clear(0xaaaaaa);
                // Nakresli usecku
                drawLine(startedPoints.x, startedPoints.y, e.getX(), e.getY(), new Color(0xFF0000), true);
            }
        });
    }

    // Pomocí Graphics vykreslí raster do panelu. Specifické pro BufferedImage
    private void present(Graphics graphics) {
        raster.repaint(graphics);
    }

    // Vykreslení úsečky jako samostatná metoda
    private void drawLine(int startX, int startY, int endX, int endY, Color color, boolean isDottedLine) {
        // Vykresluj usecku dle parametru
        System.out.println(">> Vykresluji usecku");
        System.out.println(startX + "/ " + startY + "/ " + endX + "/ " + endY + "/ " + color);

        if (isDottedLine) {
            dottedLineRasterizer.rasterize(startX, startY, endX, endY, color, true);
        } else {
            filledLineRasterizer.rasterize(startX, startY, endX, endY, color);
        }
        // Prekresli platno
        repaint(0xaaaaaa);
    }

    // Vyčistí raster danou barvou
    private void clear(int color) {
        raster.setClearColor(0xaaaaaa);
        raster.clear();
    }
    // Prekresli platno
    private void repaint(int color) {
        raster.setClearColor(color);
        panel.repaint();
    }
    // Při spuštění provedeme vyčištění rasteru a raster zobrazíme
    private void start() {
        clear(0xaaaaaa);
        panel.repaint();
    }
    // Vstupní bod do aplikace
    public static void main(String[] args) {
        // Vytvoří se instance třídy MyCanvas a zavolá se metoda start()
        SwingUtilities.invokeLater(() -> new MyCanvas(800, 600).start());
    }
}
